image: Visual Studio 2017

before_build:
  - nuget restore Semester2/Homework3/3.2/3.2.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: Semester2/Homework3/3.2/3.2.sln
  verbosity: minimal

test_script:
  - dotnet test Semester2/Homework3/3.2/3.2.sln