image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - solution: Semester4/Homework1/1.1/1.1.sln
  - solution: Semester4/Homework1/1.2/1.2.sln
  - solution: Semester4/Homework1/1.3/1.3.sln
  - solution: Semester4/Homework1/1.4/1.4.sln
  - solution: Semester4/Homework1/1.5/1.5.sln
  - solution: Semester4/Homework2/2.4/2.4.sln

before_build:
  - nuget restore %solution%

build:
  project: $(solution)

test_script:
  - dotnet test %solution%